from core import resume_handlers, job_application_handlers


HANDLERS = {
    "job_application_handlers.handle_get_job_application_report": job_application_handlers.handle_get_job_application_report,
    "job_application_handlers.handle_get_job_application_commands": job_application_handlers.handle_get_job_application_commands,
    "job_application_handlers.handle_search_job_applications": job_application_handlers.handle_search_job_applications,
    "job_application_handlers.handle_filter_job_applications": job_application_handlers.handle_filter_job_applications,
    "job_application_handlers.handle_sort_job_applications": job_application_handlers.handle_sort_job_applications,
    "job_application_handlers.handle_get_application_notes": job_application_handlers.handle_get_application_notes,
    "job_application_handlers.handle_get_application_status_timeline": job_application_handlers.handle_get_application_status_timeline,
    "job_application_handlers.handle_get_job_application_details": job_application_handlers.handle_get_job_application_details,
    "job_application_handlers.handle_get_application_interview_reminders": job_application_handlers.handle_get_application_interview_reminders,
    "job_application_handlers.handle_get_application_interview_result": job_application_handlers.handle_get_application_interview_result,
    "job_application_handlers.handle_get_application_follow_up_reminders": job_application_handlers.handle_get_application_follow_up_reminders,
    "job_application_handlers.handle_get_interview_preparation": job_application_handlers.handle_get_interview_preparation,
    "job_application_handlers.handle_get_job_offer": job_application_handlers.handle_get_job_offer,
    "job_application_handlers.handle_get_joining_checklist": job_application_handlers.handle_get_joining_checklist,
    "job_application_handlers.handle_get_joining_countdown": job_application_handlers.handle_get_joining_countdown,
    "job_application_handlers.handle_get_joining_readiness": job_application_handlers.handle_get_joining_readiness,
    "job_application_handlers.handle_get_joining_risk": job_application_handlers.handle_get_joining_risk,
    "job_application_handlers.handle_get_joining_day_assistant": job_application_handlers.handle_get_joining_day_assistant,
    "job_application_handlers.handle_get_joining_day_schedule": job_application_handlers.handle_get_joining_day_schedule,
    "job_application_handlers.handle_get_post_joining_checkin": job_application_handlers.handle_get_post_joining_checkin,
    "job_application_handlers.handle_get_new_job_success_tracker": job_application_handlers.handle_get_new_job_success_tracker,
    "job_application_handlers.handle_get_90_day_career_success_tracker": job_application_handlers.handle_get_90_day_career_success_tracker,
    "job_application_handlers.handle_get_performance_review_assistant": job_application_handlers.handle_get_performance_review_assistant,
    "job_application_handlers.handle_get_promotion_readiness": job_application_handlers.handle_get_promotion_readiness,
    "job_application_handlers.handle_get_salary_growth_analysis": job_application_handlers.handle_get_salary_growth_analysis,
    "job_application_handlers.handle_get_career_roadmap": job_application_handlers.handle_get_career_roadmap,
    "job_application_handlers.handle_get_career_skill_gap_analysis": job_application_handlers.handle_get_career_skill_gap_analysis,
    "job_application_handlers.handle_get_career_skill_development_plan": job_application_handlers.handle_get_career_skill_development_plan,
    "job_application_handlers.handle_get_career_learning_roadmap": job_application_handlers.handle_get_career_learning_roadmap,
    "job_application_handlers.handle_get_career_project_plan": job_application_handlers.handle_get_career_project_plan,
    "job_application_handlers.handle_get_career_portfolio_readiness": job_application_handlers.handle_get_career_portfolio_readiness,
    "job_application_handlers.handle_get_career_interview_readiness": job_application_handlers.handle_get_career_interview_readiness,
    "job_application_handlers.handle_get_career_resume_readiness": job_application_handlers.handle_get_career_resume_readiness,
    "job_application_handlers.handle_get_career_job_match_analysis": job_application_handlers.handle_get_career_job_match_analysis,
    "job_application_handlers.handle_get_career_job_recommendations": job_application_handlers.handle_get_career_job_recommendations,
    "job_application_handlers.handle_get_career_application_success_prediction": job_application_handlers.handle_get_career_application_success_prediction,
    "job_application_handlers.handle_get_career_offer_conversion_prediction": job_application_handlers.handle_get_career_offer_conversion_prediction,
    "job_application_handlers.handle_get_career_rejection_risk_analysis": job_application_handlers.handle_get_career_rejection_risk_analysis,
    "job_application_handlers.handle_get_career_offer_decision_analysis": job_application_handlers.handle_get_career_offer_decision_analysis,
    "job_application_handlers.handle_get_career_salary_negotiation_advice": job_application_handlers.handle_get_career_salary_negotiation_advice,
    "job_application_handlers.handle_get_career_compensation_comparison_analysis": job_application_handlers.handle_get_career_compensation_comparison_analysis,
    "job_application_handlers.handle_get_career_offer_negotiation_advice": job_application_handlers.handle_get_career_offer_negotiation_advice,
    "job_application_handlers.handle_get_career_offer_comparison_analysis": job_application_handlers.handle_get_career_offer_comparison_analysis,
    "job_application_handlers.handle_get_career_offer_acceptance_analysis": job_application_handlers.handle_get_career_offer_acceptance_analysis,
            "job_application_handlers.handle_update_career_background_document": job_application_handlers.handle_update_career_background_document,
    "job_application_handlers.handle_get_career_background_documents": job_application_handlers.handle_get_career_background_documents,
    "job_application_handlers.handle_get_career_background_submission_readiness": job_application_handlers.handle_get_career_background_submission_readiness,
    "job_application_handlers.handle_get_career_background_verification_completion": job_application_handlers.handle_get_career_background_verification_completion,
    "job_application_handlers.handle_update_career_background_verification_status": job_application_handlers.handle_update_career_background_verification_status,
    "job_application_handlers.handle_get_career_background_verification_follow_up_message": job_application_handlers.handle_get_career_background_verification_follow_up_message,
    "job_application_handlers.handle_get_career_background_verification_follow_up": job_application_handlers.handle_get_career_background_verification_follow_up,
    "job_application_handlers.handle_get_career_background_verification_progress": job_application_handlers.handle_get_career_background_verification_progress,
    "job_application_handlers.handle_update_career_background_verification_escalation_response": job_application_handlers.handle_update_career_background_verification_escalation_response,
    "job_application_handlers.handle_get_career_background_verification_escalation_response": job_application_handlers.handle_get_career_background_verification_escalation_response,
    "job_application_handlers.handle_update_career_background_verification_closure": job_application_handlers.handle_update_career_background_verification_closure,
    "job_application_handlers.handle_get_career_background_verification_closure_message": job_application_handlers.handle_get_career_background_verification_closure_message,
    "job_application_handlers.handle_get_career_background_verification_closure_analytics": job_application_handlers.handle_get_career_background_verification_closure_analytics,
    "job_application_handlers.handle_get_career_background_verification_closure_action_plan": job_application_handlers.handle_get_career_background_verification_closure_action_plan,
    "job_application_handlers.handle_get_career_background_verification_closure_dashboard": job_application_handlers.handle_get_career_background_verification_closure_dashboard,
    "job_application_handlers.handle_get_career_background_verification_closure_recommendation": job_application_handlers.handle_get_career_background_verification_closure_recommendation,
    "job_application_handlers.handle_get_career_background_verification_closure_followup_plan": job_application_handlers.handle_get_career_background_verification_closure_followup_plan,
    "job_application_handlers.handle_get_career_background_verification_closure_summary_report": job_application_handlers.handle_get_career_background_verification_closure_summary_report,
    "job_application_handlers.handle_get_career_background_verification_closure_final_decision": job_application_handlers.handle_get_career_background_verification_closure_final_decision,
    "job_application_handlers.handle_export_career_background_verification_closure_audit_trail": job_application_handlers.handle_export_career_background_verification_closure_audit_trail,
    "job_application_handlers.handle_get_career_background_verification_closure_audit_summary": job_application_handlers.handle_get_career_background_verification_closure_audit_summary,
    "job_application_handlers.handle_get_career_background_verification_closure_evidence_pack": job_application_handlers.handle_get_career_background_verification_closure_evidence_pack,
    "job_application_handlers.handle_validate_career_background_verification_closure_evidence": job_application_handlers.handle_validate_career_background_verification_closure_evidence,
    "job_application_handlers.handle_check_career_background_verification_closure_evidence_integrity": job_application_handlers.handle_check_career_background_verification_closure_evidence_integrity,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_consistency": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_consistency,
    "job_application_handlers.handle_score_career_background_verification_closure_evidence_quality": job_application_handlers.handle_score_career_background_verification_closure_evidence_quality,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_confidence": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_confidence,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_readiness": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_readiness,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_finalization": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_finalization,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_archival": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_archival,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_retention": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_retention,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_compliance": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_compliance,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_audit": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_audit,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_governance": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_governance,
    "job_application_handlers.handle_analyze_career_background_verification_closure_evidence_governance": job_application_handlers.handle_analyze_career_background_verification_closure_evidence_governance,
    "job_application_handlers.handle_get_career_background_verification_closure_risk": job_application_handlers.handle_get_career_background_verification_closure_risk,
    "job_application_handlers.handle_get_career_background_verification_closure_history": job_application_handlers.handle_get_career_background_verification_closure_history,
    "job_application_handlers.handle_get_career_background_verification_closure": job_application_handlers.handle_get_career_background_verification_closure,
    "job_application_handlers.handle_get_career_background_verification_resolution_message": job_application_handlers.handle_get_career_background_verification_resolution_message,
    "job_application_handlers.handle_get_career_background_verification_resolution": job_application_handlers.handle_get_career_background_verification_resolution,
    "job_application_handlers.handle_get_career_background_verification_escalation_message": job_application_handlers.handle_get_career_background_verification_escalation_message,
    "job_application_handlers.handle_get_career_background_verification_escalation": job_application_handlers.handle_get_career_background_verification_escalation,
    "job_application_handlers.handle_get_career_background_verification_delay_risk": job_application_handlers.handle_get_career_background_verification_delay_risk,
    "job_application_handlers.handle_get_career_background_verification_risk": job_application_handlers.handle_get_career_background_verification_risk,
    "job_application_handlers.handle_get_career_background_verification_readiness": job_application_handlers.handle_get_career_background_verification_readiness,
    "job_application_handlers.handle_get_career_employment_verification_request": job_application_handlers.handle_get_career_employment_verification_request,
    "job_application_handlers.handle_get_career_experience_certificate_request": job_application_handlers.handle_get_career_experience_certificate_request,
    "job_application_handlers.handle_get_career_relieving_letter_request": job_application_handlers.handle_get_career_relieving_letter_request,
    "job_application_handlers.handle_get_career_resignation_letter": job_application_handlers.handle_get_career_resignation_letter,
    "job_application_handlers.handle_get_career_joining_confirmation": job_application_handlers.handle_get_career_joining_confirmation,
    "job_application_handlers.handle_get_career_offer_followup": job_application_handlers.handle_get_career_offer_followup,
    "job_application_handlers.handle_get_career_acceptance_message": job_application_handlers.handle_get_career_acceptance_message,
    "job_application_handlers.handle_get_career_negotiation_script": job_application_handlers.handle_get_career_negotiation_script,
    "job_application_handlers.handle_get_career_counter_offer_analysis": job_application_handlers.handle_get_career_counter_offer_analysis,
    "job_application_handlers.handle_get_career_offer_decline_analysis": job_application_handlers.handle_get_career_offer_decline_analysis,

    "resume_handlers.handle_get_resume_intelligence_report": resume_handlers.handle_get_resume_intelligence_report,
    "resume_handlers.handle_get_resume_recommendations": resume_handlers.handle_get_resume_recommendations,
    "resume_handlers.handle_get_resume_intelligence": resume_handlers.handle_get_resume_intelligence,
    "resume_handlers.handle_get_best_resume_action": resume_handlers.handle_get_best_resume_action,
    "resume_handlers.handle_add_resume_skill": resume_handlers.handle_add_resume_skill,
    "resume_handlers.handle_set_keyword_coverage": resume_handlers.handle_set_keyword_coverage,
    "resume_handlers.handle_add_missing_keyword": resume_handlers.handle_add_missing_keyword,
    "resume_handlers.handle_clear_missing_keyword": resume_handlers.handle_clear_missing_keyword,
    "resume_handlers.handle_set_resume_target_role": resume_handlers.handle_set_resume_target_role,
    "resume_handlers.handle_set_resume_section": resume_handlers.handle_set_resume_section,
}


def get_handler(name):
    return HANDLERS.get(name)

































def handle_score_career_background_verification_closure_evidence_quality(command):
    application_id = command[
        len("career background verification closure evidence quality "):
    ].strip()

    if not application_id:
        return (
            "Usage: career background verification closure evidence quality "
            "<application_id>"
        )

    return score_career_background_verification_closure_evidence_quality(
        application_id
    )









